export const showcase = [
  {
    name: 'OpenAI / ChatGPT',
    slug: 'openai',
    thumbnail: require('@/img/showcase/thumbnails/openai.com.png').default,
    video: require('@/videos/showcase/openai.com.mp4').default,
    description: '营销网站&聊天界面',
  },
  {
    name: 'Lemon Squeezy',
    slug: 'lemon-squeezy',
    thumbnail: require('@/img/showcase/thumbnails/app.lemonsqueezy.com.png').default,
    video: require('@/videos/showcase/app.lemonsqueezy.com.mp4').default,
    description: 'SaaS应用程序',
  },
  {
    name: 'Shopify',
    slug: 'shopify',
    thumbnail: require('@/img/showcase/thumbnails/shopify.com.png').default,
    video: require('@/videos/showcase/shopify.com.mp4').default,
    description: '电子商务平台网站',
  },
  {
    name: 'Wealthfront',
    slug: 'wealthfront',
    thumbnail: require('@/img/showcase/thumbnails/wealthfront.com.png').default,
    video: require('@/videos/showcase/wealthfront.com.mp4').default,
    description: '金融科技营销网站',
  },
  {
    name: 'Netflix全球十佳',
    slug: 'netflix',
    thumbnail: require('@/img/showcase/thumbnails/top10.netflix.com.png').default,
    video: require('@/videos/showcase/top10.netflix.com.mp4').default,
    description: '微博',
  },
  {
    name: 'Loom',
    slug: 'loom',
    thumbnail: require('@/img/showcase/thumbnails/loom.com.png').default,
    video: require('@/videos/showcase/loom.com.mp4').default,
    description: 'SaaS营销网站',
  },
  {
    name: 'The Verge',
    slug: 'the-verge',
    thumbnail: require('@/img/showcase/thumbnails/theverge.com.png').default,
    video: require('@/videos/showcase/theverge.com.mp4').default,
    description: '新闻网站',
  },
  {
    name: 'Laracon Online',
    slug: 'laracon',
    thumbnail: require('@/img/showcase/thumbnails/laracon.net.png').default,
    video: require('@/videos/showcase/laracon.net.mp4').default,
    description: '会议网站',
  },
  {
    name: 'Turbo',
    slug: 'turbo',
    thumbnail: require('@/img/showcase/thumbnails/turbo.build.png').default,
    video: require('@/videos/showcase/turbo.build.mp4').default,
    description: '开发人员工具网站',
  },
  {
    name: 'candycode',
    slug: 'candycode',
    thumbnail: require('@/img/showcase/thumbnails/candycode.com.png').default,
    video: require('@/videos/showcase/candycode.com.mp4').default,
    description: '机构网站',
  },
  {
    name: 'Column',
    slug: 'column',
    thumbnail: require('@/img/showcase/thumbnails/column.com.png').default,
    video: require('@/videos/showcase/column.com.mp4').default,
    description: '金融科技营销网站',
  },
  {
    name: 'Wander',
    slug: 'wander',
    thumbnail: require('@/img/showcase/thumbnails/wander.com.png').default,
    video: require('@/videos/showcase/wander.com.mp4').default,
    description: '度假租赁网站',
  },
  {
    name: 'New York Times Events',
    slug: 'nytimes',
    thumbnail: require('@/img/showcase/thumbnails/nytimes.com.png').default,
    video: require('@/videos/showcase/nytimes.com.mp4').default,
    description: '新闻网站',
  },
  {
    name: 'GitHub Next',
    slug: 'github',
    thumbnail: require('@/img/showcase/thumbnails/githubnext.com.png').default,
    video: require('@/videos/showcase/githubnext.com.mp4').default,
    description: '研究网站',
  },
  {
    name: 'PlanetScale',
    slug: 'planetscale',
    thumbnail: require('@/img/showcase/thumbnails/planetscale.com.png').default,
    video: require('@/videos/showcase/planetscale.com.mp4').default,
    description: 'SaaS营销网站',
  },
  {
    name: 'Algolia Docs',
    slug: 'algolia',
    thumbnail: require('@/img/showcase/thumbnails/algolia.com.png').default,
    video: require('@/videos/showcase/algolia.com.mp4').default,
    description: '文档的网站',
  },
  {
    name: 'MrBeast Feastables',
    slug: 'feastables',
    thumbnail: require('@/img/showcase/thumbnails/feastables.com.png').default,
    video: require('@/videos/showcase/feastables.com.mp4').default,
    description: '直接面向消费者商店',
  },
  {
    name: 'NASA Jet Propulsion Laboratory',
    slug: 'nasa',
    thumbnail: require('@/img/showcase/thumbnails/jpl.nasa.gov.png').default,
    video: require('@/videos/showcase/jpl.nasa.gov.mp4').default,
    description: '空间实验室网站',
  },
  {
    name: 'Salient',
    slug: 'salient',
    thumbnail: require('@/img/showcase/thumbnails/salient.tailwindui.com.png').default,
    video: require('@/videos/showcase/salient.tailwindui.com.mp4').default,
    description: 'SaaS营销网站',
    isTemplate: true,
  },
  {
    name: 'Mashable',
    slug: 'mashable',
    thumbnail: require('@/img/showcase/thumbnails/mashable.com.png').default,
    video: require('@/videos/showcase/mashable.com.mp4').default,
    description: '新闻网站',
  },
  {
    name: 'Microsoft .NET',
    slug: 'dotnet',
    thumbnail: require('@/img/showcase/thumbnails/dotnet.microsoft.com.png').default,
    video: require('@/videos/showcase/dotnet.microsoft.com.mp4').default,
    description: '软件框架网站',
  },
  {
    name: 'Spotlight',
    slug: 'spotlight',
    thumbnail: require('@/img/showcase/thumbnails/spotlight.tailwindui.com.png').default,
    video: require('@/videos/showcase/spotlight.tailwindui.com.mp4').default,
    description: '个人网站',
    isTemplate: true,
    dark: {
      thumbnail: require('@/img/showcase/thumbnails/spotlight.tailwindui.com-dark.png').default,
      video: require('@/videos/showcase/spotlight.tailwindui.com-dark.mp4').default,
    },
  },
  {
    name: 'Clearbit',
    slug: 'clearbit',
    thumbnail: require('@/img/showcase/thumbnails/clearbit.com.png').default,
    video: require('@/videos/showcase/clearbit.com.mp4').default,
    description: 'SaaS营销网站',
  },
  {
    name: 'Dizzie',
    slug: 'dizzie',
    thumbnail: require('@/img/showcase/thumbnails/getdizzie.com.png').default,
    video: require('@/videos/showcase/getdizzie.com.mp4').default,
    description: '电子商务商店',
  },
  {
    name: 'Google I/O 2022',
    slug: 'google-io-2022',
    thumbnail: require('@/img/showcase/thumbnails/io.google.png').default,
    video: require('@/videos/showcase/io.google.mp4').default,
    description: '会议网站',
    dark: {
      thumbnail: require('@/img/showcase/thumbnails/io.google-dark.png').default,
      video: require('@/videos/showcase/io.google-dark.mp4').default,
    },
  },
  {
    name: 'Keynote',
    slug: 'keynote',
    thumbnail: require('@/img/showcase/thumbnails/keynote.tailwindui.com.png').default,
    video: require('@/videos/showcase/keynote.tailwindui.com.mp4').default,
    description: '会议网站',
    isTemplate: true,
  },
  {
    name: 'KeepGrading',
    slug: 'keepgrading',
    thumbnail: require('@/img/showcase/thumbnails/keepgrading.com.png').default,
    video: require('@/videos/showcase/keepgrading.com.mp4').default,
    description: '机构网站',
  },
  {
    name: 'Transmit',
    slug: 'transmit',
    thumbnail: require('@/img/showcase/thumbnails/transmit.tailwindui.com.png').default,
    video: require('@/videos/showcase/transmit.tailwindui.com.mp4').default,
    description: 'Podcast网站',
    isTemplate: true,
  },
  {
    name: 'Poolsuite Grand Leisure',
    slug: 'grand-leisure',
    thumbnail: require('@/img/showcase/thumbnails/grandleisure.org.png').default,
    video: require('@/videos/showcase/grandleisure.org.mp4').default,
    description: 'NFT营销网站',
  },
  {
    name: 'Pocket',
    slug: 'pocket',
    thumbnail: require('@/img/showcase/thumbnails/pocket.tailwindui.com.png').default,
    video: require('@/videos/showcase/pocket.tailwindui.com.mp4').default,
    description: '手机应用营销网站',
    isTemplate: true,
  },
  {
    name: 'Modern Treasury',
    slug: 'modern-treasury',
    thumbnail: require('@/img/showcase/thumbnails/moderntreasury.com.png').default,
    video: require('@/videos/showcase/moderntreasury.com.mp4').default,
    description: '金融科技营销网站',
  },
  {
    name: 'National Park Foundation',
    slug: 'national-park-foundation',
    thumbnail: require('@/img/showcase/thumbnails/nationalparks.org.png').default,
    video: require('@/videos/showcase/nationalparks.org.mp4').default,
    description: '非营利组织网站',
  },
  {
    name: 'Syntax',
    slug: 'syntax',
    thumbnail: require('@/img/showcase/thumbnails/syntax.tailwindui.com.png').default,
    video: require('@/videos/showcase/syntax.tailwindui.com.mp4').default,
    description: '文档的网站',
    isTemplate: true,
    dark: {
      thumbnail: require('@/img/showcase/thumbnails/syntax.tailwindui.com-dark.png').default,
      video: require('@/videos/showcase/syntax.tailwindui.com-dark.mp4').default,
    },
  },
  {
    name: 'SavvyCal',
    slug: 'savvycal',
    thumbnail: require('@/img/showcase/thumbnails/savvycal.com.png').default,
    video: require('@/videos/showcase/savvycal.com.mp4').default,
    description: 'SaaS应用程序',
  },
  {
    name: 'Opal',
    slug: 'opal',
    thumbnail: require('@/img/showcase/thumbnails/opalcamera.com.png').default,
    video: require('@/videos/showcase/opalcamera.com.mp4').default,
    description: '产品营销网站',
  },
  {
    name: 'Coinbase NFT',
    slug: 'coinbase',
    thumbnail: require('@/img/showcase/thumbnails/nft.coinbase.com.png').default,
    video: require('@/videos/showcase/nft.coinbase.com.mp4').default,
    description: '在线市场',
    dark: {
      thumbnail: require('@/img/showcase/thumbnails/nft.coinbase.com-dark.png').default,
      video: require('@/videos/showcase/nft.coinbase.com-dark.mp4').default,
    },
  },
  {
    name: 'Primer',
    slug: 'primer',
    thumbnail: require('@/img/showcase/thumbnails/primer.tailwindui.com.png').default,
    video: require('@/videos/showcase/primer.tailwindui.com.mp4').default,
    description: '资讯产品网站',
    isTemplate: true,
  },
  {
    name: 'Der Spiegel',
    slug: 'spiegel',
    thumbnail: require('@/img/showcase/thumbnails/spiegel.de.png').default,
    video: require('@/videos/showcase/spiegel.de.mp4').default,
    description: '新闻网站',
    dark: {
      thumbnail: require('@/img/showcase/thumbnails/spiegel.de-dark.png').default,
      video: require('@/videos/showcase/spiegel.de-dark.mp4').default,
    },
  },
]
